.github/workflows/lint_test.yaml
.github/workflows/release.yaml
README.md
charts/bc-depository/Chart.yaml
charts/bc-depository/README.md
charts/bc-depository/files/network.json
charts/bc-depository/templates/deploy.yaml
charts/bc-depository/templates/ingress.yaml
charts/bc-depository/templates/rbac.yaml
charts/bc-depository/templates/secret.yaml
charts/bc-depository/templates/service.yaml
charts/bc-depository/values.yaml
repos/repository_bitnami.yaml
repos/repository_grafana.yaml
repos/repository_kubebb.yaml

feat: add chart bc-depository and enable helm repo with github action

---

charts/bc-explorer/Chart.yaml
charts/bc-explorer/templates/_help.tpl
charts/bc-explorer/templates/deploy.yaml
charts/bc-explorer/templates/ingress.yaml
charts/bc-explorer/templates/rbac.yaml
charts/bc-explorer/templates/service.yaml
charts/bc-explorer/values.yaml

Fix: https://github.com/kubebb/components/issues/2

feat: add bc-explorer charts

---

charts/bc-explorer/values.yaml

fix: fix typo

---

examples/bc-apis/componentplan.yaml

fix: fix the componentplan of bc-apis

---

examples/cluster-component/README.md
examples/cluster-component/componentplan.yaml
examples/fabric-operator/README.md
examples/fabric-operator/componentplan.yaml
examples/u4a-component/README.md
examples/u4a-component/componentplan.yaml

feat: u4a deployment tutorial
Fix: https://github.com/kubebb/components/issues/41

feat: add component deployment requirements

---

examples/cluster-component/README.md
examples/cluster-component/componentplan.yaml
examples/u4a-component/README.md

fix: typos

---

charts/cluster-component/Chart.yaml
charts/cluster-component/values.yaml

Fix https://github.com/kubebb/core/issues/153  from component side

fix: empty field not allowed

---

charts/u4a-component/Chart.yaml
charts/u4a-component/charts/crds/Chart.yaml
charts/u4a-component/charts/crds/templates/component.t7d.io_component.yaml

Fix: https://github.com/kubebb/core/issues/155

fix: remove preset fields from metadata to avoid patch failures

---

examples/cluster-component/README.md
examples/cluster-component/componentplan.yaml
examples/fabric-operator/README.md
examples/u4a-component/README.md
examples/u4a-component/componentplan.yaml

Fix: https://github.com/kubebb/components/issues/6

fix: use flag wait on u4a-component deployment

---

charts/chartmuseum/.helmignore
charts/chartmuseum/Chart.yaml
charts/chartmuseum/LICENSE
charts/chartmuseum/README.md
charts/chartmuseum/ci/ingress-values.yaml
charts/chartmuseum/templates/NOTES.txt
charts/chartmuseum/templates/_helpers.tpl
charts/chartmuseum/templates/deployment.yaml
charts/chartmuseum/templates/ingress.yaml
charts/chartmuseum/templates/pv.yaml
charts/chartmuseum/templates/pvc.yaml
charts/chartmuseum/templates/secret.yaml
charts/chartmuseum/templates/service.yaml
charts/chartmuseum/templates/serviceaccount.yaml
charts/chartmuseum/templates/servicemonitor.yaml
charts/chartmuseum/values.yaml

feat:add a new component named chartmuseum
Fix: #54

feat:add a new component named chartmuseum

---

examples/jupyterlab/README.md
examples/jupyterlab/componentplan.yaml
repos/repository_arcadia.yaml

feat: enable kubeagi components into kubebb

---

charts/u4a-component/Chart.yaml
charts/u4a-component/templates/post-create-menu.yaml
charts/u4a-component/values.yaml

fix: use kubebb menus in u4a-compnent
Fix: https://github.com/kubebb/components/issues/62

fix: use kubebb menus in u4a-compnent

---

charts/kubebb-core/Chart.yaml
charts/kubebb-core/crds/core.kubebb.k8s.com.cn_componentplans.yaml
charts/kubebb-core/crds/core.kubebb.k8s.com.cn_menus.yaml
charts/kubebb-core/crds/core.kubebb.k8s.com.cn_portals.yaml
charts/kubebb-core/crds/core.kubebb.k8s.com.cn_repositories.yaml
charts/kubebb-core/crds/core.kubebb.k8s.com.cn_subscriptions.yaml
charts/kubebb-core/values.yaml

🤖 Auto Sync Kubebb Core release v0.1.3

---

charts/kubebb-core/Chart.yaml
charts/kubebb-core/templates/cert-manager-ca-issuer.yaml
charts/kubebb-core/templates/cert-manager-ca.yaml
charts/kubebb-core/templates/deployment.yaml
charts/kubebb-core/templates/webhook_manifests.yaml
charts/kubebb-core/templates/webhook_service.yaml
charts/kubebb-core/values.yaml

fix: sync webhook.
@Abirdcfly @bjwswang How to generate certificate for webhook?

fix: sync webhook

---

charts/chartmuseum/Chart.yaml
charts/chartmuseum/values.yaml
examples/chartmuseum/README.md
examples/chartmuseum/componentplan.yaml
examples/chartmuseum/componentplan_auth.yaml
examples/chartmuseum/repository_chartmuseum.yaml

feat: add a componentplan example
Fix: #77

feat: add a componentplan example

---

charts/kubebb-core/Chart.yaml
charts/kubebb-core/templates/deployment.yaml
charts/kubebb-core/templates/pipelinerun_clusterrole.yaml
charts/kubebb-core/templates/pipelinerun_clusterrolebinding.yaml
charts/kubebb-core/templates/pipelinerun_serviceaccount.yaml
charts/kubebb-core/values.yaml

Fix:  https://github.com/kubebb/core/issues/249

feat: add Rating deployment logic

---

charts/kubebb-core/Chart.yaml
charts/kubebb-core/templates/_help.tpl
charts/kubebb-core/templates/deployment.yaml
charts/kubebb-core/templates/rating_clusterrole.yaml
charts/kubebb-core/templates/rating_clusterrolebinding.yaml
charts/kubebb-core/templates/rating_serviceaccount.yaml

chore: update rating environment variable definition

chore: update rating environment variable definition

---

.github/PULL_REQUEST_TEMPLATE.md
charts/kubebb-core/Chart.yaml
charts/kubebb-core/templates/post-repo-kubebb.yaml

feat: post create kubebb repo after kubebb-core installed

---

charts/u4a-component/Chart.yaml
charts/u4a-component/templates/post-create-menu.yaml
charts/u4a-component/values.yaml

chore: update u4a-component to support menu management

---

examples/arcadia/README.md
examples/arcadia/componentplan.yaml
examples/arcadia/subscription.yaml

feat: add examples for deploying arcadia with kubebb

---

charts/bc-apis/Chart.yaml
charts/bc-depository/Chart.yaml
charts/bc-explorer/Chart.yaml
charts/kubebb-core/Chart.yaml
charts/u4a-component/Chart.yaml
charts/u4a-component/charts/addon-component/Chart.yaml
charts/u4a-component/charts/addon-component/templates/kube-oidc-proxy/audit-policy-configmap.yaml
examples/bc-apis/componentplan.yaml

chore: use strict semver in kubebb components

---

repos/repository_kubebb.yaml

feat: add displayName for repository

---

charts/kubebb-core/Chart.yaml
charts/kubebb-core/crds/core.kubebb.k8s.com.cn_components.yaml
charts/kubebb-core/crds/core.kubebb.k8s.com.cn_ratings.yaml
charts/kubebb-core/templates/webhook_manifests.yaml
charts/kubebb-core/values.yaml

feat: sync kubebb-core chart

---

charts/component-store/Chart.yaml
charts/component-store/README.md
charts/component-store/templates/configmap.yaml
charts/component-store/templates/deployment.yaml
charts/component-store/templates/ingress.yaml
charts/component-store/templates/menu.yaml
charts/component-store/templates/portal.yaml
charts/component-store/templates/service.yaml
charts/component-store/values.yaml
examples/component-store/README.md
examples/component-store/componentplan.yaml

/kind feature
add the component-store chart 
Fixes #

feat: add the component-store chart

---

charts/kubebb-core/Chart.yaml
charts/kubebb-core/templates/pipeline-security.yaml

/kind feature
feat: support storing rbac yaml content in configmap.
Fixes #
```yaml
root@macbookpro:/# kubectl get cm kubebb.kubebb-core.v0.1.10 -nkubebb-system -oyaml
apiVersion: v1
binaryData:
r: ZGlncmFwaCAgewoJc3ViZ3JhcGggY2x1c3Rlcl9zMCB7CgkJSUQgPSAiY2x1c3Rlcl9zMCI7CgkJc3ViZ3JhcGggY2x1c3Rlcl9zMCB7CgkJCUlEID0gImNsdXN0ZXJfczAiOwoJCQlsYWJlbD0iTmFtZXNwYWNlIjtzdHlsZT0iZGFzaGVkIjsKCQkJbjJbY29sb3I9InJlZCIsZmlsbGNvbG9yPSIjMmY2ZGUxIixmb250Y29sb3I9IiMwMzAzMDMiLGxhYmVsPSJNaXNzaW5nIFN1YmplY3RcbihLaW5kKSIscGVud2lkdGg9IjIuMCIsc2hhcGU9ImJveCIsc3R5bGU9ImRvdHRlZCJdOwoJCQluMVtjb2xvcj0iYmxhY2siLGZpbGxjb2xvcj0iIzJmNmRlMSIsZm9udGNvbG9yPSIjZjBmMGYwIixsYWJlbD0iU3ViamVjdFxuKEtpbmQpIixwZW53aWR0aD0iMS4wIixzaGFwZT0iYm94IixzdHlsZT0iZmlsbGVkIl07CgkJCW40W2NvbG9yPSJibGFjayIsZmlsbGNvbG9yPSIjZmY5OTAwIixmb250Y29sb3I9Ii …
```

feat: support storing rbac yaml content in configmap

---

charts/minio/Chart.yaml
charts/minio/values.yaml
examples/chartmuseum/README.md
examples/chartmuseum/componentplan_auth.yaml
examples/chartmuseum/repository_chartmuseum.yaml
examples/chartmuseum/repository_chartmuseum_auth.yaml
examples/minio/componentplan.yaml

chore: use standalone by default in minio

---

charts/kubebb-core/Chart.yaml
charts/kubebb-core/templates/deployment.yaml

feat: add localtime mount to kubebb-core

---

examples/arcadia/componentplan.yaml
examples/arcadia/subscription.yaml

chore: use arcadia in kubebb-addons

---

charts/kubebb-core/Chart.yaml
charts/kubebb-core/crds/core.kubebb.k8s.com.cn_repositories.yaml

feat: sync kubebb-core chart crd

---

examples/chartmuseum/componentplan_auth.yaml
examples/chartmuseum/repository_chartmuseum_auth.yaml

fix: invalid name for chartmuseum_auth

---

charts/hello-world/Chart.yaml
charts/hello-world/README.md
charts/hello-world/templates/deployment.yaml
charts/hello-world/templates/ingress.yaml
charts/hello-world/templates/menu.yaml
charts/hello-world/templates/portal.yaml
charts/hello-world/templates/service.yaml
charts/hello-world/values.yaml
examples/hello-world/componentplan.yaml

feat: add hello-world example for kubebb component

---

charts/component-store/Chart.yaml
charts/component-store/templates/menu.yaml

/kind bug
Adjust the menu
Fixes #

fix: adjust the menu of component-store

---

charts/kubebb-core/Chart.yaml
charts/kubebb-core/templates/deployment.yaml

fix(kubebb-core): add POD_NAME and POD_NAMESPACE env

---

.gitignore
charts/kubebb-core/Chart.yaml
charts/kubebb-core/templates/role_template.yaml

/kind feature
Fixes #
see https://shimo.im/sheets/erAdMJozBMIx0L3G/MODOC And https://portal.172.22.96.136.nip.io/oidc/management/clusters/cluster-wmhvq/role-template/detail/kubebb

feat(kubebb-core): add roletemplate

---

charts/kubebb-core/Chart.yaml
charts/kubebb-core/crds/core.kubebb.k8s.com.cn_componentplans.yaml
charts/kubebb-core/crds/core.kubebb.k8s.com.cn_components.yaml
charts/kubebb-core/crds/core.kubebb.k8s.com.cn_ratings.yaml
charts/kubebb-core/crds/core.kubebb.k8s.com.cn_subscriptions.yaml
charts/kubebb-core/values.yaml

🤖 Auto Sync Kubebb Core release v0.1.6

---

charts/cluster-component/Chart.yaml
charts/u4a-component/Chart.yaml

chore: bump chart versions

---

.github/workflows/release.yaml

chore: bump helm/chart-releaser-action to latest

---

charts/hello-world/Chart.yaml
charts/hello-world/values.yaml

chore: enable ingress in hello-world by default

---

charts/kubebb-core/Chart.yaml
charts/kubebb-core/templates/post-repo-kubebb.yaml

chore: set repo kubebb to official by default

---

charts/u4a-component/Chart.lock
charts/u4a-component/Chart.yaml
charts/u4a-component/charts/crds/Chart.yaml
charts/u4a-component/charts/crds/templates/iam.tenxcloud.com_groups.yaml
examples/u4a-component/componentplan.yaml

fix: add crd groups for u4a-component

---

examples/u4a-component/README.md

add link for values.yaml in README.md
/kind documentation
Fixes #

add link for values.yaml in README.md

---

charts/kubebb-core/Chart.yaml
charts/kubebb-core/templates/pipeline-reliability.yaml
charts/kubebb-core/templates/pipeline-security.yaml

/kind bug
fix: change the task name of the component rating
Fixes #

fix: change the task name of the component rating

---

charts/u4a-component/Chart.lock
charts/u4a-component/Chart.yaml
charts/u4a-component/charts/addon-component/Chart.yaml
charts/u4a-component/charts/addon-component/templates/kube-oidc-proxy/kube-oidc-proxy.yaml

/kind bug
Fix the configuration in u4a-component/kube-oidc-proxy.yaml
Fixes #

fix: Fix the configuration in u4a-component/kube-oidc-proxy.yaml

---

charts/cluster-component/Chart.yaml
charts/cluster-component/values.yaml

chore: use kubebb as the cluster component image repo

---

charts/u4a-component/Chart.yaml
charts/u4a-component/templates/bff-server/redis.yaml

chore: use IfNotPresent as default image pull policy for redis

---

charts/u4a-component/Chart.yaml

Update the chart version to 0.2.4
/kind bug
Fixes #
see [https://github.com/kubebb/components/pull/173](https://github.com/kubebb/components/pull/173)

Update the chart version to 0.2.4

---

charts/u4a-component/Chart.yaml
charts/u4a-component/templates/bff-server/bff-server-config.yaml
charts/u4a-component/values.yaml

Fixes #
@Carrotzpc  Please review

configure bff-server's session.cookie.domain

---

charts/u4a-component/Chart.yaml
charts/u4a-component/templates/bff-server/bff-server-config.yaml
charts/u4a-component/templates/bff-server/bff-server.yaml
charts/u4a-component/templates/bff-server/portal-global-configs.yaml

feat(bff-server): add global-configs and fix logos path issue

---

charts/u4a-component/Chart.yaml
charts/u4a-component/templates/resource-view/view-controller-deploy.yaml
charts/u4a-component/values.yaml

fix: add more host aliases

---

charts/kubebb-core/Chart.yaml
charts/kubebb-core/templates/pipeline-security.yaml
charts/kubebb-core/templates/rating_clusterrole.yaml

/kind bug
fix: delete rating also delete reports
Fixes #

fix: delete rating also delete reports

---

charts/u4a-component/Chart.yaml
charts/u4a-component/values.yaml

/kind bug
fix: fix hostaliases issues
Fixes #
```shell
NAME                                                          READY   STATUS    RESTARTS   AGE
bff-server-74c79c8b66-4c7cr                                   1/1     Running   0          105s
bff-server-session-redis-7f89d6b98d-lfn2g                     1/1     Running   0          105s
capsule-controller-manager-855748f996-wnsqr                   1/1     Running   0          105s
cert-manager-659f5ccfb6-np6r6                                 1/1     Running   0          157m
cert-manager-cainjector-58cb7b7f9c-w9brn                      1/1     Running   0          157m
cert-manager-webhook-574d56876f-nb6g4                         1/1     Running   0          157m
cluster-component-ingress-nginx-controller-744fd95c66-t9rqv   1/1 …
```

fix: fix hostaliases issues

---

charts/u4a-component/Chart.yaml
charts/u4a-component/templates/bff-server/bff-server-config.yaml

/kind bug
chore: configure k8s connection method
Fixes #

chore: configure k8s connection method
